---
Name: silverstripe-search-service-elastic
Only:
  envvarset: 'ENTERPRISE_SEARCH_API_KEY'
After:
  - 'silverstripe-search-service-dataobject'
  - 'search-service-default'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\SearchService\Interfaces\IndexingInterface:
    class: SilverStripe\SearchServiceElastic\Service\EnterpriseSearchService
    constructor:
      client: '%$Elastic\EnterpriseSearch\Client'
      configuration: '%$SilverStripe\SearchService\Service\IndexConfiguration'
      builder: '%$SilverStripe\SearchService\Service\DocumentBuilder'
  Elastic\EnterpriseSearch\Client:
    factory: SilverStripe\SearchServiceElastic\Service\ClientFactory
    constructor:
      host: '`ENTERPRISE_SEARCH_ENDPOINT`'
      token: '`ENTERPRISE_SEARCH_API_KEY`'
      http_client: '%$GuzzleHttp\Client'

## customise the dataobject fields for EnterpriseSearch compatability
SilverStripe\SearchService\DataObject\DataObjectDocument:
  id_field: record_id
  base_class_field: record_base_class
  page_content_field: page_content
